stages:
- build
- package

binaries:
  stage: build
  script:
  - nix build -Lf ./release.nix image
  - cp -Lr result image
  artifacts:
    name: "haskell-tools-$CI_BUILD_ID"
    paths:
    - image
  tags:
  - coinmetrics-nix-build-runner

.docker-image:
  stage: package
  image: docker:latest
  services:
  - docker:dind
  dependencies:
  - binaries
  script:
  - cp Dockerfile bin/
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest bin
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  - docker push $CI_REGISTRY_IMAGE:latest
  tags:
  - linux
  - docker
  only:
  - master
