stages:
- build
- package

nix-image:
  stage: build
  script:
  - nix build -Lf ./release.nix --argstr name $CI_REGISTRY_IMAGE --argstr tag nix image
  - skopeo copy --dest-creds gitlab-ci-token:$CI_JOB_TOKEN docker-archive:result docker://$CI_REGISTRY_IMAGE:nix
  tags:
  - coinmetrics-nix-build-runner

.docker-image:
  stage: package
  image: docker:latest
  services:
  - docker:dind
  dependencies:
  - binaries
  script:
  - cp Dockerfile bin/
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest bin
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  - docker push $CI_REGISTRY_IMAGE:latest
  tags:
  - linux
  - docker
  only:
  - master
