stages:
- build

nix-image:
  stage: build
  script:
  - nix build -Lf ./release.nix --argstr name $CI_REGISTRY_IMAGE --argstr tag nix image
  - export SKOPEO=$(nix-build --no-out-link -QA tools.skopeo ./release.nix)/bin/skopeo
  - $SKOPEO copy --dest-creds $DOCKERHUB_USERNAME:$DOCKERHUB_PASSWORD docker-archive:result docker://$DOCKERHUB_IMAGE
  - $SKOPEO copy --dest-creds gitlab-ci-token:$CI_JOB_TOKEN docker-archive:result docker://$CI_REGISTRY_IMAGE:nix
  tags:
  - coinmetrics-nix-build-runner
  only:
  - master

nix-image-mr:
  stage: build
  script:
  - nix build -Lf ./release.nix --argstr name $CI_REGISTRY_IMAGE --argstr tag nix image
  tags:
  - coinmetrics-nix-build-runner
  only:
  - merge_requests
