stages:
- build

nix-image:
  stage: build
  script:
  - nix build -Lf ./release.nix image
  - $(nix-build --no-out-link -QA tools.skopeo ./release.nix)/bin/skopeo copy --dest-creds $DOCKERHUB_USERNAME:$DOCKERHUB_PASSWORD docker-archive:result docker://$DOCKERHUB_IMAGE
  tags:
  - coinmetrics-nix-build-runner
  only:
  - master

nix-image-mr:
  stage: build
  script:
  - nix build -Lf ./release.nix nix image
  tags:
  - coinmetrics-nix-build-runner
  only:
  - merge_requests
