stages:
- build

nix-image:
  stage: build
  script:
  - $(nix-build --no-out-link -QA pushImagesScript ./release.nix)
  tags:
  - coinmetrics-nix-build-runner
  only:
  - master

nix-image-mr:
  stage: build
  script:
  - nix-build --no-out-link -QA pushImagesScript ./release.nix
  tags:
  - coinmetrics-nix-build-runner
  only:
  - merge_requests
